### ISSUE TITLE
1.1 update

### ISSUE THREAD

**Issue by rachelf42** [MarcGamesons/factoriomod-cheaper-landfill#22]
pls and ty

**Comment by SGZ-Creations** [comment]
When is this being done ? if at all other wise can u ask some to take over the maintenance of it

**Comment by ChaoticWeg** [comment]
I just opened a pull request that updates game files to allow them to work with the current version of Factorio at time of writing. Tested and it's working fine without any changes to Lua code. @MarcGamesons

**Comment by MarcGamesons** [comment]
Thanks for updating the mod to 1.1.

@all-contributors please add @ChaoticWeg for maintenance.

**Comment by MarcGamesons** [comment]
I will create a release for https://mods.factorio.com/mod/cheaper_landfill/downloads shortly.

**Comment by ChaoticWeg** [comment]
No problem! Glad to help. Thanks for taking care of the release.

**Comment by MarcGamesons** [comment]
The mod should now be available ingame for download and updates. If not simply open a new issue here on GitHub.
