### ISSUE TITLE
Error by Gamestart

### ISSUE THREAD

**Issue by xXDarkNovaXx** [MarcGamesons/factoriomod-cheaper-landfill#25]
I think this Problem is a Modconflict but i have no found the Problem

![Screenshot_7](https://user-images.githubusercontent.com/22129313/112425895-2cd7f400-8d37-11eb-8fab-acb67ec31f1c.png)

**Comment by MarcGamesons** [comment]
Yes, this looks like a mod conflict. Do you have any mods installed that add landfill or water tiles?

**Comment by MarcGamesons** [comment]
@xXDarkNovaXx Any news on which mod could cause the issue?

**Comment by xXDarkNovaXx** [comment]
I have no idea if any other mod adds water or land
But I also have problems with other mods that only the mod developer can fix because I don't know much about programming
So I'm currently forced to continue playing with 1.0
This conflict does not occur until version 1.1
